dist: bionic

language: go
go: 1.13.1

services:
  - docker

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t maslick/beanstalker .

after_success:
  - test $TRAVIS_BRANCH = "master" && docker push maslick/beanstalker